### ISSUE TITLE
Опечатка в определении условной информации по Хартли

### ISSUE THREAD

**Issue by gnull** [avsmal/information-theory-notes#1]
Александр Владимирович,

https://github.com/avsmal/information-theory-notes/blob/3d94b702d3aee67ee2a0ba5e28b6e67e11e7783a/information-theory.tex#L123

Кажется, тут имеется ввиду, что A_a = {(a′, x) ∈ A ∣ a′ = a}. Верно?

Написанное в конспекте сейчас означает, что A_a = {a} × π₂(A). Поэтому |A_a| = |π₂(A)| — размер A_a не зависит от a.

Иван

**Comment by avsmal** [comment]
Спасибо, поправил.
