### ISSUE TITLE
Нужно оценить ошибку, вносимую округлением

### ISSUE THREAD

**Issue by gnull** [avsmal/information-theory-notes#2]
Александр Владимирович,

https://github.com/avsmal/information-theory-notes/blob/590472ebd11179fcaa839ee9e69713264ce9bbf7/information-theory.tex#L164

В этом параграфе нельзя одновременно сказать, что |X \cap T| = \alpha|X|, и что \alpha=(\sqrt 5 - 1) / 2. Первое требует, чтобы \alpha|X| было целым, а второе выбирает такое значение для \alpha, что это не выполняется.

Понятно, что тут имеется ввиду, что на самом деле будет выбираться какое-то близкое к (\sqrt 5 - 1) / 2 число, которое получится округлением вверх/вниз до ближайшего кратного |X \cap T| / |X|. Но по-честному нужно как-то оценить эту ошибку при округлении и её влияние на доказываемую верхнюю оценку. Мне сходу непонятно, как это сделать, и я даже не совсем уверен, что это получится.

Иван

**Comment by avsmal** [comment]
Да, вы правы. Таня Белова мне про это тоже говорила, но руки не дошли. Сделаю. В книжке Верещагина эта проблема описана и приведена соответствующая оценка (стр. 90-91).
